[package]
name = "app-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app-core = {path = "../app-core" }
actix-cors = "0.5.4"
actix-web = "3.3.2"
juniper_actix = "0.2.3"
dotenv = "0.15.0"